### PR TITLE
Enable Shippable for rabbitmq

### PR DESCRIPTION
**Pull request by gundalow**
##### SUMMARY
Basic Shippable configuration for rabbitmq, based on community.general.

Enabling codecoverage is future work.

Fixes: #1 

##### ISSUE TYPE
- Feature Pull Request

### CODE REVIEW

**Comment by gundalow** [comment]
@odyssey4me hum, so this is a bit more involved than I originally thought. I'll keep chipping away at it.

**Comment by odyssey4me** [comment]
Thanks @gundalow - I really appreciate you taking the time to help!

**Comment by odyssey4me** [comment]
@gundalow I'll work out the integration test issue, but could do with help on the sanity/unit test issues.

**Comment by gundalow** [comment]
Hi, does my comment on https://github.com/ansible-collections/libvirt/pull/2 help?

**Comment by odyssey4me** [comment]
@gundalow Hooray, test parity for ansible/ansible. :)

**Comment by gundalow** [comment]
Amazing. That's a major milestone.

**Pull request merged**
